### ISSUE TITLE
Does not work with Diagrams 1.3

### ISSUE THREAD

**Issue by cchens** [Courseography/courseography#568]
Doing `runhaskell server.hs` with diagrams-1.3 yields the following error:

`Diagram.hs:59:42: Not in scope: data constructor ‘Width’`

As far as I can tell the issue is with the recent diagrams package update, as it runs fine on my other laptop with diagrams-1.2.0 installed

**Comment by christinem** [comment]
Looks like there's a change to the API which makes the Diagrams.hs file break. 

Here, you can see that they changed `Width` to `mkWidth` in the change from `diagrams-1.2` to 'diagrams-1.3`.

https://wiki.haskell.org/Diagrams/Dev/Migrate1.3

**Comment by christinem** [comment]
The second error I'm guessing is probably because of this change listed on the webpage:

> The Diagram alias has also changed. It no longer takes a vector space as a parameter; it simply uses the default space and number type for the backend parameter:

Diagram b = QDiagram b (V b) (N b) Any

where V b is the default space and N b is the default number type for backend b. This means you should replace e.g.

Diagram Cairo R2 -> Diagram Cairo
